/* 越南语生活高频词（按主题分组，第一波约 120 词；后续可继续补充到 300–500）
   数据结构：VN_TOPIC_WORDS = [{ cat, icon, words:[{ vn, zh, ex? }] }]
   ex 为可选：该词的实用例句 { vn, zh }，用于口语练习「💡 例句」展开。
   本文件在 app.js 之前加载，VN_TOPIC_WORDS 为全局变量。 */
const VN_TOPIC_WORDS = [
  { cat: '问候与社交', icon: '👋', words: [
    { vn: 'Xin chào', zh: '你好', ex: { vn: 'Xin chào, tôi là Lan.', zh: '你好，我是兰。' } },
    { vn: 'Tạm biệt', zh: '再见', ex: { vn: 'Tạm biệt, hẹn gặp lại!', zh: '再见，回头见！' } },
    { vn: 'Cảm ơn', zh: '谢谢', ex: { vn: 'Cảm ơn bạn rất nhiều.', zh: '非常感谢你。' } },
    { vn: 'Không có gì', zh: '不客气', ex: { vn: 'Cảm ơn bạn. — Không có gì.', zh: '谢谢你。——不客气。' } },
    { vn: 'Xin lỗi', zh: '对不起', ex: { vn: 'Xin lỗi, tôi đến muộn.', zh: '对不起，我迟到了。' } },
    { vn: 'Tên tôi là…', zh: '我叫……', ex: { vn: 'Tên tôi là Hoàng, rất vui được gặp bạn.', zh: '我叫黄，很高兴认识你。' } },
    { vn: 'Bạn tên là gì?', zh: '你叫什么名字？', ex: { vn: 'Bạn tên là gì? Tên tôi là Mai.', zh: '你叫什么名字？我叫梅。' } },
    { vn: 'Rất vui được gặp bạn.', zh: '很高兴认识你。', ex: { vn: 'Rất vui được gặp bạn hôm nay.', zh: '今天很高兴认识你。' } },
    { vn: 'Không sao.', zh: '没关系。', ex: { vn: 'Không sao, tôi ổn.', zh: '没关系，我没事。' } },
    { vn: 'Bạn khỏe không?', zh: '你好吗？', ex: { vn: 'Bạn khỏe không? Tôi khỏe, cảm ơn.', zh: '你好吗？我很好，谢谢。' } },
  ]},
  { cat: '餐饮', icon: '🍜', words: [
    { vn: 'Phở', zh: '河粉', ex: { vn: 'Cho tôi một bát phở.', zh: '给我一碗河粉。' } },
    { vn: 'Cơm', zh: '米饭', ex: { vn: 'Tôi ăn cơm tối.', zh: '我吃晚饭。' } },
    { vn: 'Bánh mì', zh: '面包', ex: { vn: 'Tôi mua một ổ bánh mì.', zh: '我买一个面包。' } },
    { vn: 'Nước', zh: '水', ex: { vn: 'Tôi muốn một chai nước.', zh: '我要一瓶水。' } },
    { vn: 'Cà phê', zh: '咖啡', ex: { vn: 'Tôi uống cà phê buổi sáng.', zh: '我早上喝咖啡。' } },
    { vn: 'Trà', zh: '茶', ex: { vn: 'Tôi thích uống trà.', zh: '我喜欢喝茶。' } },
    { vn: 'Thịt', zh: '肉', ex: { vn: 'Thịt này ngon.', zh: '这肉很好吃。' } },
    { vn: 'Cá', zh: '鱼', ex: { vn: 'Tôi ăn cá.', zh: '我吃鱼。' } },
    { vn: 'Rau', zh: '蔬菜', ex: { vn: 'Tôi ăn nhiều rau.', zh: '我吃很多蔬菜。' } },
    { vn: 'Ngon', zh: '好吃', ex: { vn: 'Món này ngon quá!', zh: '这道菜太好吃了！' } },
  ]},
  { cat: '住宿', icon: '🛏️', words: [
    { vn: 'Khách sạn', zh: '酒店', ex: { vn: 'Khách sạn này đẹp.', zh: '这家酒店很漂亮。' } },
    { vn: 'Phòng', zh: '房间', ex: { vn: 'Phòng của tôi ở tầng ba.', zh: '我的房间在 3 楼。' } },
    { vn: 'Nhà', zh: '房子', ex: { vn: 'Nhà tôi ở Hà Nội.', zh: '我家在河内。' } },
    { vn: 'Giường', zh: '床', ex: { vn: 'Giường này thoải mái.', zh: '这张床很舒服。' } },
    { vn: 'Nhà vệ sinh', zh: '厕所', ex: { vn: 'Nhà vệ sinh ở đâu?', zh: '厕所在哪里？' } },
    { vn: 'Nóng', zh: '热', ex: { vn: 'Hôm nay trời nóng.', zh: '今天天气热。' } },
    { vn: 'Lạnh', zh: '冷', ex: { vn: 'Mùa đông rất lạnh.', zh: '冬天很冷。' } },
    { vn: 'Sạch', zh: '干净', ex: { vn: 'Phòng rất sạch.', zh: '房间很干净。' } },
    { vn: 'Bẩn', zh: '脏', ex: { vn: 'Tay tôi bẩn.', zh: '我的手脏了。' } },
    { vn: 'Chìa khóa', zh: '钥匙', ex: { vn: 'Chìa khóa ở đâu?', zh: '钥匙在哪？' } },
  ]},
  { cat: '交通出行', icon: '🚕', words: [
    { vn: 'Xe buýt', zh: '公交车', ex: { vn: 'Tôi đi xe buýt.', zh: '我坐公交车。' } },
    { vn: 'Xe taxi', zh: '出租车', ex: { vn: 'Tôi gọi một chiếc taxi.', zh: '我叫一辆出租车。' } },
    { vn: 'Xe máy', zh: '摩托车', ex: { vn: 'Anh ấy đi xe máy.', zh: '他骑摩托车。' } },
    { vn: 'Sân bay', zh: '机场', ex: { vn: 'Sân bay ở đâu?', zh: '机场在哪里？' } },
    { vn: 'Ga tàu', zh: '火车站', ex: { vn: 'Ga tàu ở gần đây.', zh: '火车站在这附近。' } },
    { vn: 'Đi', zh: '去', ex: { vn: 'Tôi đi Việt Nam.', zh: '我去越南。' } },
    { vn: 'Đến', zh: '到', ex: { vn: 'Tôi đến khách sạn rồi.', zh: '我到酒店了。' } },
    { vn: 'Về', zh: '回', ex: { vn: 'Tôi về nhà.', zh: '我回家。' } },
    { vn: 'Trạm dừng', zh: '车站', ex: { vn: 'Trạm dừng ở đằng kia.', zh: '车站在那边。' } },
    { vn: 'Vé', zh: '票', ex: { vn: 'Tôi mua một vé.', zh: '我买一张票。' } },
  ]},
  { cat: '购物', icon: '🛍️', words: [
    { vn: 'Tiền', zh: '钱', ex: { vn: 'Tôi trả tiền.', zh: '我付钱。' } },
    { vn: 'Bao nhiêu', zh: '多少', ex: { vn: 'Cái này bao nhiêu tiền?', zh: '这个多少钱？' } },
    { vn: 'Đắt', zh: '贵', ex: { vn: 'Quá đắt!', zh: '太贵了！' } },
    { vn: 'Rẻ', zh: '便宜', ex: { vn: 'Cái này rất rẻ.', zh: '这个很便宜。' } },
    { vn: 'Mua', zh: '买', ex: { vn: 'Tôi muốn mua cái này.', zh: '我想买这个。' } },
    { vn: 'Bán', zh: '卖', ex: { vn: 'Cửa hàng bán gì?', zh: '商店卖什么？' } },
    { vn: 'Chợ', zh: '市场', ex: { vn: 'Tôi đi chợ sáng.', zh: '我早上去市场。' } },
    { vn: 'Cửa hàng', zh: '商店', ex: { vn: 'Cửa hàng mở cửa rồi.', zh: '商店开门了。' } },
    { vn: 'Màu', zh: '颜色', ex: { vn: 'Màu này đẹp.', zh: '这个颜色好看。' } },
    { vn: 'Kích thước', zh: '尺寸', ex: { vn: 'Kích thước bao nhiêu?', zh: '尺寸是多少？' } },
  ]},
  { cat: '健康医疗', icon: '💊', words: [
    { vn: 'Bác sĩ', zh: '医生', ex: { vn: 'Tôi cần gặp bác sĩ.', zh: '我需要看医生。' } },
    { vn: 'Thuốc', zh: '药', ex: { vn: 'Tôi uống thuốc.', zh: '我吃药。' } },
    { vn: 'Bệnh viện', zh: '医院', ex: { vn: 'Tôi đến bệnh viện.', zh: '我去医院。' } },
    { vn: 'Đau', zh: '疼', ex: { vn: 'Tôi bị đau đầu.', zh: '我头疼。' } },
    { vn: 'Sốt', zh: '发烧', ex: { vn: 'Tôi bị sốt.', zh: '我发烧了。' } },
    { vn: 'Mệt', zh: '累', ex: { vn: 'Tôi mệt quá.', zh: '我好累。' } },
    { vn: 'Cứu', zh: '救', ex: { vn: 'Cứu tôi với!', zh: '救命！' } },
    { vn: 'Hiệu thuốc', zh: '药店', ex: { vn: 'Hiệu thuốc ở đâu?', zh: '药店在哪？' } },
    { vn: 'Tiêm', zh: '打针', ex: { vn: 'Tôi cần tiêm.', zh: '我需要打针。' } },
    { vn: 'Nhức', zh: '痛', ex: { vn: 'Tôi bị nhức đầu.', zh: '我头疼。' } },
  ]},
  { cat: '人物与称谓', icon: '👨‍👩‍👧', words: [
    { vn: 'Tôi', zh: '我', ex: { vn: 'Tôi là người Trung Quốc.', zh: '我是中国人。' } },
    { vn: 'Bạn', zh: '你 / 朋友', ex: { vn: 'Bạn là bạn tốt của tôi.', zh: '你是我的好朋友。' } },
    { vn: 'Anh', zh: '哥哥 / 你（男）', ex: { vn: 'Anh khỏe không?', zh: '你好吗？（对男性）' } },
    { vn: 'Chị', zh: '姐姐 / 你（女）', ex: { vn: 'Chị khỏe không?', zh: '你好吗？（对女性）' } },
    { vn: 'Em', zh: '弟弟 / 妹妹', ex: { vn: 'Em khỏe không?', zh: '你好吗？（对晚辈）' } },
    { vn: 'Bố', zh: '爸爸', ex: { vn: 'Bố tôi khỏe.', zh: '我爸爸身体好。' } },
    { vn: 'Mẹ', zh: '妈妈', ex: { vn: 'Mẹ tôi nấu ăn ngon.', zh: '我妈妈做饭好吃。' } },
    { vn: 'Con', zh: '孩子', ex: { vn: 'Tôi có hai con.', zh: '我有两个孩子。' } },
    { vn: 'Người', zh: '人', ex: { vn: 'Người này rất tốt.', zh: '这个人很好。' } },
    { vn: 'Gia đình', zh: '家庭', ex: { vn: 'Gia đình tôi vui vẻ.', zh: '我家很和睦。' } },
  ]},
  { cat: '时间与数字', icon: '⏰', words: [
    { vn: 'Hôm nay', zh: '今天', ex: { vn: 'Hôm nay trời đẹp.', zh: '今天天气好。' } },
    { vn: 'Ngày', zh: '天', ex: { vn: 'Tôi tập mỗi ngày.', zh: '我每天锻炼。' } },
    { vn: 'Tháng', zh: '月', ex: { vn: 'Tháng này tôi bận.', zh: '这个月我很忙。' } },
    { vn: 'Năm', zh: '年', ex: { vn: 'Chúc mừng năm mới!', zh: '新年快乐！' } },
    { vn: 'Giờ', zh: '小时 / 钟点', ex: { vn: 'Bây giờ là mấy giờ?', zh: '现在几点？' } },
    { vn: 'Sáng', zh: '早上', ex: { vn: 'Sáng nay tôi chạy bộ.', zh: '今天早上我跑步。' } },
    { vn: 'Chiều', zh: '下午', ex: { vn: 'Chiều nay tôi rảnh.', zh: '今天下午我有空。' } },
    { vn: 'Tối', zh: '晚上', ex: { vn: 'Tối nay xem phim.', zh: '今晚看电影。' } },
    { vn: 'Một', zh: '一', ex: { vn: 'Tôi có một quyển sách.', zh: '我有一本书。' } },
    { vn: 'Hai', zh: '二', ex: { vn: 'Tôi có hai con mèo.', zh: '我有两只猫。' } },
  ]},
  { cat: '天气与自然', icon: '🌤️', words: [
    { vn: 'Trời', zh: '天 / 天气', ex: { vn: 'Trời đẹp quá!', zh: '天气真好！' } },
    { vn: 'Mưa', zh: '雨', ex: { vn: 'Hôm nay trời mưa.', zh: '今天下雨。' } },
    { vn: 'Nắng', zh: '晴', ex: { vn: 'Trời nắng đẹp.', zh: '晴天很美。' } },
    { vn: 'Gió', zh: '风', ex: { vn: 'Gió thổi mạnh.', zh: '风很大。' } },
    { vn: 'Núi', zh: '山', ex: { vn: 'Núi cao quá.', zh: '山好高。' } },
    { vn: 'Sông', zh: '河', ex: { vn: 'Sông này dài.', zh: '这条河很长。' } },
    { vn: 'Biển', zh: '海', ex: { vn: 'Biển xanh quá.', zh: '海好蓝。' } },
    { vn: 'Cây', zh: '树', ex: { vn: 'Cây này to.', zh: '这棵树很大。' } },
    { vn: 'Hoa', zh: '花', ex: { vn: 'Hoa đẹp quá.', zh: '花好漂亮。' } },
    { vn: 'Mặt trời', zh: '太阳', ex: { vn: 'Mặt trời mọc rồi.', zh: '太阳升起来了。' } },
  ]},
  { cat: '常用动词', icon: '💬', words: [
    { vn: 'Ăn', zh: '吃', ex: { vn: 'Tôi ăn phở.', zh: '我吃河粉。' } },
    { vn: 'Uống', zh: '喝', ex: { vn: 'Tôi uống nước.', zh: '我喝水。' } },
    { vn: 'Ngủ', zh: '睡', ex: { vn: 'Tôi ngủ sớm.', zh: '我早睡。' } },
    { vn: 'Thích', zh: '喜欢', ex: { vn: 'Tôi thích Việt Nam.', zh: '我喜欢越南。' } },
    { vn: 'Biết', zh: '知道', ex: { vn: 'Bạn có biết không?', zh: '你知道吗？' } },
    { vn: 'Hiểu', zh: '懂', ex: { vn: 'Tôi hiểu rồi.', zh: '我懂了。' } },
    { vn: 'Nói', zh: '说', ex: { vn: 'Bạn nói tiếng Anh không?', zh: '你会说英语吗？' } },
    { vn: 'Nghe', zh: '听', ex: { vn: 'Tôi nghe nhạc.', zh: '我听音乐。' } },
    { vn: 'Xem', zh: '看', ex: { vn: 'Tôi xem ti vi.', zh: '我看电视。' } },
    { vn: 'Làm', zh: '做', ex: { vn: 'Tôi làm việc.', zh: '我工作。' } },
  ]},
  { cat: '方位与疑问', icon: '📍', words: [
    { vn: 'Đâu', zh: '哪里', ex: { vn: 'Nhà vệ sinh ở đâu?', zh: '厕所在哪里？' } },
    { vn: 'Đây', zh: '这里', ex: { vn: 'Đây là nhà tôi.', zh: '这是我家。' } },
    { vn: 'Đó', zh: '那里', ex: { vn: 'Đó là trường học.', zh: '那是学校。' } },
    { vn: 'Trái', zh: '左', ex: { vn: 'Rẽ trái.', zh: '向左转。' } },
    { vn: 'Phải', zh: '右', ex: { vn: 'Rẽ phải.', zh: '向右转。' } },
    { vn: 'Trước', zh: '前', ex: { vn: 'Đứng trước cửa.', zh: '站在门前。' } },
    { vn: 'Sau', zh: '后', ex: { vn: 'Sau nhà có một cái cây.', zh: '屋后有一棵树。' } },
    { vn: 'Gần', zh: '近', ex: { vn: 'Gần đây thôi.', zh: '就在附近。' } },
    { vn: 'Xa', zh: '远', ex: { vn: 'Xa quá.', zh: '太远了。' } },
    { vn: 'Trên', zh: '上', ex: { vn: 'Sách ở trên bàn.', zh: '书在桌子上。' } },
  ]},
  { cat: '旅行实用', icon: '🎒', words: [
    { vn: 'Hộ chiếu', zh: '护照', ex: { vn: 'Tôi mất hộ chiếu.', zh: '我丢了护照。' } },
    { vn: 'Visa', zh: '签证', ex: { vn: 'Tôi cần làm visa.', zh: '我需要办签证。' } },
    { vn: 'Vali', zh: '行李箱', ex: { vn: 'Vali nặng quá.', zh: '行李箱好重。' } },
    { vn: 'Quà', zh: '礼物', ex: { vn: 'Tôi mua quà cho bạn.', zh: '我给你买礼物。' } },
    { vn: 'Ảnh', zh: '照片', ex: { vn: 'Chụp ảnh nhé!', zh: '拍照吧！' } },
    { vn: 'Bản đồ', zh: '地图', ex: { vn: 'Xem bản đồ đi.', zh: '看地图吧。' } },
    { vn: 'Danh bạ', zh: '通讯录', ex: { vn: 'Mở danh bạ.', zh: '打开通讯录。' } },
    { vn: 'Điện thoại', zh: '电话', ex: { vn: 'Điện thoại của tôi hỏng.', zh: '我的电话坏了。' } },
    { vn: 'Internet', zh: '网络', ex: { vn: 'Internet chậm quá.', zh: '网络太慢了。' } },
    { vn: 'Sim', zh: '电话卡', ex: { vn: 'Tôi mua một chiếc sim.', zh: '我买一张电话卡。' } },
  ]},
];
