/* 越南语生活高频词（按主题分组，已扩充到约 380 词，覆盖吃喝/交通/购物/应急等场景）
   数据结构：VN_TOPIC_WORDS = [{ cat, icon, words:[{ vn, zh, ex? }] }]
   ex 为可选：该词的实用例句 { vn, zh }，用于口语练习「💡 例句」展开。
   本文件在 app.js 之前加载，VN_TOPIC_WORDS 为全局变量。
   注意：新增词汇的发音音频由 scripts/gen_vn_audio.py 自动生成（前缀 NX_），
         VN_AUDIO_MAP 会自动为未映射的词分配 NX_ 序号，请勿手写 NW_/NX_ 映射。 */
const VN_TOPIC_WORDS = [
  { cat: '问候与社交', icon: '👋', words: [
    { vn: 'Xin chào', zh: '你好', ex: { vn: 'Xin chào, tôi là Lan.', zh: '你好，我是兰。' } },
    { vn: 'Tạm biệt', zh: '再见', ex: { vn: 'Tạm biệt, hẹn gặp lại!', zh: '再见，回头见！' } },
    { vn: 'Cảm ơn', zh: '谢谢', ex: { vn: 'Cảm ơn bạn rất nhiều.', zh: '非常感谢你。' } },
    { vn: 'Không có gì', zh: '不客气', ex: { vn: 'Cảm ơn bạn. — Không có gì.', zh: '谢谢你。——不客气。' } },
    { vn: 'Xin lỗi', zh: '对不起', ex: { vn: 'Xin lỗi, tôi đến muộn.', zh: '对不起，我迟到了。' } },
    { vn: 'Tên tôi là…', zh: '我叫……', ex: { vn: 'Tên tôi là Hoàng, rất vui được gặp bạn.', zh: '我叫黄，很高兴认识你。' } },
    { vn: 'Bạn tên là gì?', zh: '你叫什么名字？', ex: { vn: 'Bạn tên là gì? Tên tôi là Mai.', zh: '你叫什么名字？我叫梅。' } },
    { vn: 'Rất vui được gặp bạn.', zh: '很高兴认识你。', ex: { vn: 'Rất vui được gặp bạn hôm nay.', zh: '今天很高兴认识你。' } },
    { vn: 'Không sao.', zh: '没关系。', ex: { vn: 'Không sao, tôi ổn.', zh: '没关系，我没事。' } },
    { vn: 'Bạn khỏe không?', zh: '你好吗？', ex: { vn: 'Bạn khỏe không? Tôi khỏe, cảm ơn.', zh: '你好吗？我很好，谢谢。' } },
    { vn: 'Chào buổi sáng', zh: '早上好', ex: { vn: 'Chào buổi sáng, một ngày tốt lành!', zh: '早上好，祝一天愉快！' } },
    { vn: 'Chào buổi tối', zh: '晚上好', ex: { vn: 'Chào buổi tối, bạn ăn tối chưa?', zh: '晚上好，你吃晚饭了吗？' } },
    { vn: 'Chúc ngủ ngon', zh: '晚安', ex: { vn: 'Chúc ngủ ngon, hẹn mai gặp lại.', zh: '晚安，明天见。' } },
    { vn: 'Chúc may mắn', zh: '祝你好运', ex: { vn: 'Chúc bạn may mắn trong kỳ thi!', zh: '祝你考试好运！' } },
    { vn: 'Làm ơn', zh: '请', ex: { vn: 'Làm ơn cho tôi một ly nước.', zh: '请给我一杯水。' } },
    { vn: 'Cảm ơn rất nhiều', zh: '非常感谢', ex: { vn: 'Cảm ơn rất nhiều vì sự giúp đỡ.', zh: '非常感谢你的帮助。' } },
    { vn: 'Rất hân hạnh', zh: '很荣幸', ex: { vn: 'Rất hân hạnh được gặp bạn.', zh: '很荣幸认识你。' } },
    { vn: 'Xin phép', zh: '借过/告辞', ex: { vn: 'Xin phép, tôi đi trước.', zh: '失陪，我先走了。' } },
    { vn: 'Có chuyện gì không?', zh: '有什么事吗？', ex: { vn: 'Có chuyện gì không? Bạn trông buồn.', zh: '有什么事吗？你看起来不开心。' } },
    { vn: 'Giúp tôi một chút', zh: '帮我一下', ex: { vn: 'Làm ơn giúp tôi một chút.', zh: '请帮我一下。' } },
    { vn: 'Tôi hiểu rồi', zh: '我明白了', ex: { vn: 'À, tôi hiểu rồi, cảm ơn.', zh: '啊，我明白了，谢谢。' } },
    { vn: 'Hẹn gặp lại', zh: '回头见', ex: { vn: 'Hôm nay thế thôi, hẹn gặp lại!', zh: '今天就到这，回头见！' } },
  ]},
  { cat: '餐饮（吃喝）', icon: '🍜', words: [
    { vn: 'Phở', zh: '河粉', ex: { vn: 'Cho tôi một bát phở.', zh: '给我一碗河粉。' } },
    { vn: 'Cơm', zh: '米饭', ex: { vn: 'Tôi ăn cơm tối.', zh: '我吃晚饭。' } },
    { vn: 'Bánh mì', zh: '面包', ex: { vn: 'Tôi mua một ổ bánh mì.', zh: '我买一个面包。' } },
    { vn: 'Nước', zh: '水', ex: { vn: 'Tôi muốn một chai nước.', zh: '我要一瓶水。' } },
    { vn: 'Cà phê', zh: '咖啡', ex: { vn: 'Tôi uống cà phê buổi sáng.', zh: '我早上喝咖啡。' } },
    { vn: 'Trà', zh: '茶', ex: { vn: 'Tôi thích uống trà.', zh: '我喜欢喝茶。' } },
    { vn: 'Thịt', zh: '肉', ex: { vn: 'Thịt này ngon.', zh: '这肉很好吃。' } },
    { vn: 'Cá', zh: '鱼', ex: { vn: 'Tôi ăn cá.', zh: '我吃鱼。' } },
    { vn: 'Rau', zh: '蔬菜', ex: { vn: 'Tôi ăn nhiều rau.', zh: '我吃很多蔬菜。' } },
    { vn: 'Ngon', zh: '好吃', ex: { vn: 'Món này ngon quá!', zh: '这道菜太好吃了！' } },
    { vn: 'Cơm tấm', zh: '碎米饭', ex: { vn: 'Ở Sài Gòn người ta hay ăn cơm tấm.', zh: '在西贡人们常吃碎米饭。' } },
    { vn: 'Bún', zh: '米粉', ex: { vn: 'Bún bò Huế rất cay.', zh: '顺化牛肉米粉很辣。' } },
    { vn: 'Cháo', zh: '粥', ex: { vn: 'Lúc ốm tôi hay ăn cháo.', zh: '生病时我常喝粥。' } },
    { vn: 'Trứng', zh: '蛋', ex: { vn: 'Tôi ăn trứng mỗi sáng.', zh: '我每天早上吃蛋。' } },
    { vn: 'Gà', zh: '鸡', ex: { vn: 'Gà rán rất ngon.', zh: '炸鸡很好吃。' } },
    { vn: 'Bò', zh: '牛/牛肉', ex: { vn: 'Thịt bò này mềm.', zh: '这牛肉很嫩。' } },
    { vn: 'Tôm', zh: '虾', ex: { vn: 'Tôm hùm rất đắt.', zh: '龙虾很贵。' } },
    { vn: 'Canh', zh: '汤', ex: { vn: 'Mời bạn ăn canh.', zh: '请你喝汤。' } },
    { vn: 'Muối', zh: '盐', ex: { vn: 'Cho thêm chút muối.', zh: '再加点盐。' } },
    { vn: 'Đường', zh: '糖', ex: { vn: 'Cà phê có đường không?', zh: '咖啡加糖吗？' } },
    { vn: 'Ớt', zh: '辣椒', ex: { vn: 'Tôi không ăn được ớt.', zh: '我吃不了辣椒。' } },
    { vn: 'Bia', zh: '啤酒', ex: { vn: 'Uống một cốc bia không?', zh: '喝杯啤酒吗？' } },
    { vn: 'Rượu', zh: '酒', ex: { vn: 'Rượu gạo của Việt Nam rất nổi tiếng.', zh: '越南的米酒很有名。' } },
    { vn: 'Hoa quả', zh: '水果', ex: { vn: 'Sau bữa ăn ăn hoa quả nhé.', zh: '饭后吃水果吧。' } },
    { vn: 'Ăn sáng', zh: '吃早餐', ex: { vn: 'Sáng nay tôi ăn phở.', zh: '今天早上我吃河粉。' } },
    { vn: 'Ăn chay', zh: '吃素', ex: { vn: 'Thứ Hai tôi thường ăn chay.', zh: '周一我通常吃素。' } },
  ]},
  { cat: '住宿', icon: '🛏️', words: [
    { vn: 'Khách sạn', zh: '酒店', ex: { vn: 'Khách sạn này đẹp.', zh: '这家酒店很漂亮。' } },
    { vn: 'Phòng', zh: '房间', ex: { vn: 'Phòng của tôi ở tầng ba.', zh: '我的房间在 3 楼。' } },
    { vn: 'Nhà', zh: '房子', ex: { vn: 'Nhà tôi ở Hà Nội.', zh: '我家在河内。' } },
    { vn: 'Giường', zh: '床', ex: { vn: 'Giường này thoải mái.', zh: '这张床很舒服。' } },
    { vn: 'Nhà vệ sinh', zh: '厕所', ex: { vn: 'Nhà vệ sinh ở đâu?', zh: '厕所在哪里？' } },
    { vn: 'Nóng', zh: '热', ex: { vn: 'Hôm nay trời nóng.', zh: '今天天气热。' } },
    { vn: 'Lạnh', zh: '冷', ex: { vn: 'Mùa đông rất lạnh.', zh: '冬天很冷。' } },
    { vn: 'Sạch', zh: '干净', ex: { vn: 'Phòng rất sạch.', zh: '房间很干净。' } },
    { vn: 'Bẩn', zh: '脏', ex: { vn: 'Tay tôi bẩn.', zh: '我的手脏了。' } },
    { vn: 'Chìa khóa', zh: '钥匙', ex: { vn: 'Chìa khóa ở đâu?', zh: '钥匙在哪？' } },
    { vn: 'Nhà nghỉ', zh: '旅馆', ex: { vn: 'Nhà nghỉ này rẻ và sạch.', zh: '这家旅馆便宜又干净。' } },
    { vn: 'Phòng tắm', zh: '浴室', ex: { vn: 'Phòng tắm ở cuối hành lang.', zh: '浴室在走廊尽头。' } },
    { vn: 'Máy lạnh', zh: '空调', ex: { vn: 'Bật máy lạnh đi, nóng quá.', zh: '开空调吧，太热了。' } },
    { vn: 'Quạt', zh: '风扇', ex: { vn: 'Dùng quạt cho mát.', zh: '用风扇凉快些。' } },
    { vn: 'Khăn', zh: '毛巾', ex: { vn: 'Cho tôi một cái khăn.', zh: '给我一条毛巾。' } },
    { vn: 'Xà phòng', zh: '肥皂', ex: { vn: 'Xà phòng ở trong phòng tắm.', zh: '肥皂在浴室里。' } },
    { vn: 'Giặt ủi', zh: '洗衣熨烫', ex: { vn: 'Khách sạn có dịch vụ giặt ủi.', zh: '酒店有洗衣服务。' } },
    { vn: 'Đặt phòng', zh: '订房', ex: { vn: 'Tôi muốn đặt phòng hai đêm.', zh: '我想订两晚的房间。' } },
  ]},
  { cat: '交通出行', icon: '🚕', words: [
    { vn: 'Xe buýt', zh: '公交车', ex: { vn: 'Tôi đi xe buýt.', zh: '我坐公交车。' } },
    { vn: 'Xe taxi', zh: '出租车', ex: { vn: 'Tôi gọi một chiếc taxi.', zh: '我叫一辆出租车。' } },
    { vn: 'Xe máy', zh: '摩托车', ex: { vn: 'Anh ấy đi xe máy.', zh: '他骑摩托车。' } },
    { vn: 'Sân bay', zh: '机场', ex: { vn: 'Sân bay ở đâu?', zh: '机场在哪里？' } },
    { vn: 'Ga tàu', zh: '火车站', ex: { vn: 'Ga tàu ở gần đây.', zh: '火车站在这附近。' } },
    { vn: 'Đi', zh: '去', ex: { vn: 'Tôi đi Việt Nam.', zh: '我去越南。' } },
    { vn: 'Đến', zh: '到', ex: { vn: 'Tôi đến khách sạn rồi.', zh: '我到酒店了。' } },
    { vn: 'Về', zh: '回', ex: { vn: 'Tôi về nhà.', zh: '我回家。' } },
    { vn: 'Trạm dừng', zh: '车站', ex: { vn: 'Trạm dừng ở đằng kia.', zh: '车站在那边。' } },
    { vn: 'Vé', zh: '票', ex: { vn: 'Tôi mua một vé.', zh: '我买一张票。' } },
    { vn: 'Xe đạp', zh: '自行车', ex: { vn: 'Tôi đạp xe đi làm.', zh: '我骑车上班。' } },
    { vn: 'Tàu hỏa', zh: '火车', ex: { vn: 'Tàu hỏa chạy chậm hơn máy bay.', zh: '火车比飞机慢。' } },
    { vn: 'Đường', zh: '道路', ex: { vn: 'Đường này đông quá.', zh: '这条路太堵了。' } },
    { vn: 'Phố', zh: '街道', ex: { vn: 'Phố cổ Hà Nội rất đẹp.', zh: '河内的老街很美。' } },
    { vn: 'Bến xe', zh: '汽车站', ex: { vn: 'Bến xe khách ở ngoại thành.', zh: '客运站在郊区。' } },
    { vn: 'Đi bộ', zh: '步行', ex: { vn: 'Chúng ta đi bộ nhé?', zh: '我们走路去吧？' } },
    { vn: 'Lên', zh: '上（车/楼）', ex: { vn: 'Lên xe đi!', zh: '上车吧！' } },
    { vn: 'Xuống', zh: '下（车）', ex: { vn: 'Xuống xe tại trạm sau.', zh: '下一站下车。' } },
    { vn: 'Bến tàu', zh: '码头', ex: { vn: 'Bến tàu ở ngay bờ sông.', zh: '码头就在河边。' } },
    { vn: 'Đi muộn', zh: '迟到', ex: { vn: 'Xin lỗi, tôi đi muộn.', zh: '对不起，我迟到了。' } },
  ]},
  { cat: '购物', icon: '🛍️', words: [
    { vn: 'Tiền', zh: '钱', ex: { vn: 'Tôi trả tiền.', zh: '我付钱。' } },
    { vn: 'Bao nhiêu', zh: '多少', ex: { vn: 'Cái này bao nhiêu tiền?', zh: '这个多少钱？' } },
    { vn: 'Đắt', zh: '贵', ex: { vn: 'Quá đắt!', zh: '太贵了！' } },
    { vn: 'Rẻ', zh: '便宜', ex: { vn: 'Cái này rất rẻ.', zh: '这个很便宜。' } },
    { vn: 'Mua', zh: '买', ex: { vn: 'Tôi muốn mua cái này.', zh: '我想买这个。' } },
    { vn: 'Bán', zh: '卖', ex: { vn: 'Cửa hàng bán gì?', zh: '商店卖什么？' } },
    { vn: 'Chợ', zh: '市场', ex: { vn: 'Tôi đi chợ sáng.', zh: '我早上去市场。' } },
    { vn: 'Cửa hàng', zh: '商店', ex: { vn: 'Cửa hàng mở cửa rồi.', zh: '商店开门了。' } },
    { vn: 'Màu', zh: '颜色', ex: { vn: 'Màu này đẹp.', zh: '这个颜色好看。' } },
    { vn: 'Kích thước', zh: '尺寸', ex: { vn: 'Kích thước bao nhiêu?', zh: '尺寸是多少？' } },
    { vn: 'Siêu thị', zh: '超市', ex: { vn: 'Tôi đi siêu thị mua đồ.', zh: '我去超市买东西。' } },
    { vn: 'Thử', zh: '试（穿/用）', ex: { vn: 'Tôi muốn thử cái áo này.', zh: '我想试这件衣服。' } },
    { vn: 'Giảm giá', zh: '打折', ex: { vn: 'Hôm nay giảm giá 30%.', zh: '今天打七折。' } },
    { vn: 'Thanh toán', zh: '付款', ex: { vn: 'Tôi thanh toán bằng thẻ.', zh: '我用卡付款。' } },
    { vn: 'Túi', zh: '袋子/包', ex: { vn: 'Cho tôi một cái túi.', zh: '给我一个袋子。' } },
    { vn: 'Đổi trả', zh: '退换', ex: { vn: 'Tôi muốn đổi cái này.', zh: '我想换这个。' } },
    { vn: 'Hết hàng', zh: '售罄', ex: { vn: 'Món này hết hàng rồi.', zh: '这款卖完了。' } },
    { vn: 'Tôi mặc bao nhiêu?', zh: '我穿多大码？', ex: { vn: 'Tôi mặc bao nhiêu? — Cô ấy mặc M.', zh: '我穿多大码？——她穿 M 码。' } },
    { vn: 'Có không?', zh: '有吗？', ex: { vn: 'Cái nhỏ hơn có không?', zh: '有更小的吗？' } },
    { vn: 'Lấy cái này', zh: '要这个', ex: { vn: 'Tôi lấy cái này, bao nhiêu?', zh: '我要这个，多少钱？' } },
  ]},
  { cat: '健康医疗', icon: '💊', words: [
    { vn: 'Bác sĩ', zh: '医生', ex: { vn: 'Tôi cần gặp bác sĩ.', zh: '我需要看医生。' } },
    { vn: 'Thuốc', zh: '药', ex: { vn: 'Tôi uống thuốc.', zh: '我吃药。' } },
    { vn: 'Bệnh viện', zh: '医院', ex: { vn: 'Tôi đến bệnh viện.', zh: '我去医院。' } },
    { vn: 'Đau', zh: '疼', ex: { vn: 'Tôi bị đau đầu.', zh: '我头疼。' } },
    { vn: 'Sốt', zh: '发烧', ex: { vn: 'Tôi bị sốt.', zh: '我发烧了。' } },
    { vn: 'Mệt', zh: '累', ex: { vn: 'Tôi mệt quá.', zh: '我好累。' } },
    { vn: 'Cứu', zh: '救', ex: { vn: 'Cứu tôi với!', zh: '救命！' } },
    { vn: 'Hiệu thuốc', zh: '药店', ex: { vn: 'Hiệu thuốc ở đâu?', zh: '药店在哪？' } },
    { vn: 'Tiêm', zh: '打针', ex: { vn: 'Tôi cần tiêm.', zh: '我需要打针。' } },
    { vn: 'Nhức', zh: '痛', ex: { vn: 'Tôi bị nhức đầu.', zh: '我头疼。' } },
    { vn: 'Răng', zh: '牙', ex: { vn: 'Răng tôi đau.', zh: '我牙疼。' } },
    { vn: 'Bụng', zh: '肚子', ex: { vn: 'Tôi đau bụng.', zh: '我肚子疼。' } },
    { vn: 'Ho', zh: '咳嗽', ex: { vn: 'Tôi bị ho mấy ngày.', zh: '我咳了好几天。' } },
    { vn: 'Buồn nôn', zh: '恶心', ex: { vn: 'Tôi thấy buồn nôn.', zh: '我觉得恶心。' } },
    { vn: 'Dị ứng', zh: '过敏', ex: { vn: 'Tôi dị ứng với hải sản.', zh: '我对海鲜过敏。' } },
    { vn: 'Cấp cứu', zh: '急救', ex: { vn: 'Gọi cấp cứu ngay!', zh: '快叫急救！' } },
    { vn: 'Tôi bị ốm', zh: '我生病了', ex: { vn: 'Hôm nay tôi bị ốm.', zh: '今天我生病了。' } },
    { vn: 'Uống thuốc', zh: '吃药', ex: { vn: 'Ngày uống thuốc mấy lần?', zh: '一天吃几次药？' } },
    { vn: 'Khỏe lại', zh: '康复', ex: { vn: 'Chúc bạn sớm khỏe lại.', zh: '祝你早日康复。' } },
    { vn: 'Nghỉ ngơi', zh: '休息', ex: { vn: 'Bạn nên nghỉ ngơi.', zh: '你应该休息。' } },
  ]},
  { cat: '人物与称谓', icon: '👨‍👩‍👧', words: [
    { vn: 'Tôi', zh: '我', ex: { vn: 'Tôi là người Trung Quốc.', zh: '我是中国人。' } },
    { vn: 'Bạn', zh: '你 / 朋友', ex: { vn: 'Bạn là bạn tốt của tôi.', zh: '你是我的好朋友。' } },
    { vn: 'Anh', zh: '哥哥 / 你（男）', ex: { vn: 'Anh khỏe không?', zh: '你好吗？（对男性）' } },
    { vn: 'Chị', zh: '姐姐 / 你（女）', ex: { vn: 'Chị khỏe không?', zh: '你好吗？（对女性）' } },
    { vn: 'Em', zh: '弟弟 / 妹妹', ex: { vn: 'Em khỏe không?', zh: '你好吗？（对晚辈）' } },
    { vn: 'Bố', zh: '爸爸', ex: { vn: 'Bố tôi khỏe.', zh: '我爸爸身体好。' } },
    { vn: 'Mẹ', zh: '妈妈', ex: { vn: 'Mẹ tôi nấu ăn ngon.', zh: '我妈妈做饭好吃。' } },
    { vn: 'Con', zh: '孩子', ex: { vn: 'Tôi có hai con.', zh: '我有两个孩子。' } },
    { vn: 'Người', zh: '人', ex: { vn: 'Người này rất tốt.', zh: '这个人很好。' } },
    { vn: 'Gia đình', zh: '家庭', ex: { vn: 'Gia đình tôi vui vẻ.', zh: '我家很和睦。' } },
    { vn: 'Ông', zh: '爷爷/先生', ex: { vn: 'Ông nội tôi 70 tuổi.', zh: '我爷爷70岁。' } },
    { vn: 'Bà', zh: '奶奶/女士', ex: { vn: 'Bà nội tôi nấu phở ngon.', zh: '我奶奶河粉做得好。' } },
    { vn: 'Cháu', zh: '孙子/侄辈', ex: { vn: 'Cháu tôi học lớp một.', zh: '我侄子上一年级。' } },
    { vn: 'Bạn trai', zh: '男朋友', ex: { vn: 'Đây là bạn trai tôi.', zh: '这是我男朋友。' } },
    { vn: 'Bạn gái', zh: '女朋友', ex: { vn: 'Tôi có bạn gái rồi.', zh: '我有女朋友了。' } },
    { vn: 'Vợ', zh: '妻子', ex: { vn: 'Vợ tôi là giáo viên.', zh: '我妻子是老师。' } },
    { vn: 'Chồng', zh: '丈夫', ex: { vn: 'Chồng tôi làm kỹ sư.', zh: '我丈夫是工程师。' } },
    { vn: 'Bạn thân', zh: '闺蜜/死党', ex: { vn: 'Cô ấy là bạn thân của tôi.', zh: '她是我闺蜜。' } },
    { vn: 'Hàng xóm', zh: '邻居', ex: { vn: 'Hàng xóm rất thân thiện.', zh: '邻居很友好。' } },
    { vn: 'Người lạ', zh: '陌生人', ex: { vn: 'Đừng nói chuyện với người lạ.', zh: '别和陌生人说话。' } },
  ]},
  { cat: '时间与数字', icon: '⏰', words: [
    { vn: 'Hôm nay', zh: '今天', ex: { vn: 'Hôm nay trời đẹp.', zh: '今天天气好。' } },
    { vn: 'Ngày', zh: '天', ex: { vn: 'Tôi tập mỗi ngày.', zh: '我每天锻炼。' } },
    { vn: 'Tháng', zh: '月', ex: { vn: 'Tháng này tôi bận.', zh: '这个月我很忙。' } },
    { vn: 'Năm', zh: '年', ex: { vn: 'Chúc mừng năm mới!', zh: '新年快乐！' } },
    { vn: 'Giờ', zh: '小时 / 钟点', ex: { vn: 'Bây giờ là mấy giờ?', zh: '现在几点？' } },
    { vn: 'Sáng', zh: '早上', ex: { vn: 'Sáng nay tôi chạy bộ.', zh: '今天早上我跑步。' } },
    { vn: 'Chiều', zh: '下午', ex: { vn: 'Chiều nay tôi rảnh.', zh: '今天下午我有空。' } },
    { vn: 'Tối', zh: '晚上', ex: { vn: 'Tối nay xem phim.', zh: '今晚看电影。' } },
    { vn: 'Một', zh: '一', ex: { vn: 'Tôi có một quyển sách.', zh: '我有一本书。' } },
    { vn: 'Hai', zh: '二', ex: { vn: 'Tôi có hai con mèo.', zh: '我有两只猫。' } },
    { vn: 'Ba', zh: '三', ex: { vn: 'Chúng tôi có ba người.', zh: '我们有三个人。' } },
    { vn: 'Bốn', zh: '四', ex: { vn: 'Bốn quyển vở.', zh: '四本笔记本。' } },
    { vn: 'Năm', zh: '五', ex: { vn: 'Năm ngón tay.', zh: '五个手指。' } },
    { vn: 'Sáu', zh: '六', ex: { vn: 'Sáu giờ sáng.', zh: '早上六点。' } },
    { vn: 'Bảy', zh: '七', ex: { vn: 'Thứ bảy là cuối tuần.', zh: '周六是周末。' } },
    { vn: 'Tám', zh: '八', ex: { vn: 'Tám trăm nghìn đồng.', zh: '八十万越南盾。' } },
    { vn: 'Chín', zh: '九', ex: { vn: 'Chín tháng mười.', zh: '九月十号。' } },
    { vn: 'Mười', zh: '十', ex: { vn: 'Mười phút nữa.', zh: '再过十分钟。' } },
    { vn: 'Thứ hai', zh: '星期一', ex: { vn: 'Thứ hai tôi đi làm.', zh: '周一我去上班。' } },
    { vn: 'Cuối tuần', zh: '周末', ex: { vn: 'Cuối tuần tôi đi chơi.', zh: '周末我去玩。' } },
    { vn: 'Bây giờ', zh: '现在', ex: { vn: 'Bây giờ mấy giờ?', zh: '现在几点？' } },
    { vn: 'Sớm', zh: '早', ex: { vn: 'Tôi dậy rất sớm.', zh: '我起得很早。' } },
  ]},
  { cat: '天气与自然', icon: '🌤️', words: [
    { vn: 'Trời', zh: '天 / 天气', ex: { vn: 'Trời đẹp quá!', zh: '天气真好！' } },
    { vn: 'Mưa', zh: '雨', ex: { vn: 'Hôm nay trời mưa.', zh: '今天下雨。' } },
    { vn: 'Nắng', zh: '晴', ex: { vn: 'Trời nắng đẹp.', zh: '晴天很美。' } },
    { vn: 'Gió', zh: '风', ex: { vn: 'Gió thổi mạnh.', zh: '风很大。' } },
    { vn: 'Núi', zh: '山', ex: { vn: 'Núi cao quá.', zh: '山好高。' } },
    { vn: 'Sông', zh: '河', ex: { vn: 'Sông này dài.', zh: '这条河很长。' } },
    { vn: 'Biển', zh: '海', ex: { vn: 'Biển xanh quá.', zh: '海好蓝。' } },
    { vn: 'Cây', zh: '树', ex: { vn: 'Cây này to.', zh: '这棵树很大。' } },
    { vn: 'Hoa', zh: '花', ex: { vn: 'Hoa đẹp quá.', zh: '花好漂亮。' } },
    { vn: 'Mặt trời', zh: '太阳', ex: { vn: 'Mặt trời mọc rồi.', zh: '太阳升起来了。' } },
    { vn: 'Mây', zh: '云', ex: { vn: 'Mây trắng trên trời.', zh: '天上白云。' } },
    { vn: 'Tuyết', zh: '雪', ex: { vn: 'Miền Bắc có tuyết.', zh: '北方下雪。' } },
    { vn: 'Sương', zh: '雾', ex: { vn: 'Sáng nay có sương mù.', zh: '今早有雾。' } },
    { vn: 'Bão', zh: '台风', ex: { vn: 'Có bão lớn tuần này.', zh: '这周有大台风。' } },
    { vn: 'Hồ', zh: '湖', ex: { vn: 'Hồ Hoàn Kiếm ở Hà Nội.', zh: '还剑湖在河内。' } },
    { vn: 'Đảo', zh: '岛', ex: { vn: 'Đảo Phú Quốc rất đẹp.', zh: '富国岛很美。' } },
    { vn: 'Bầu trời', zh: '天空', ex: { vn: 'Bầu trời xanh thẳm.', zh: '湛蓝的天空。' } },
    { vn: 'Khí hậu', zh: '气候', ex: { vn: 'Khí hậu ở đây nóng.', zh: '这里气候炎热。' } },
  ]},
  { cat: '常用动词', icon: '💬', words: [
    { vn: 'Ăn', zh: '吃', ex: { vn: 'Tôi ăn phở.', zh: '我吃河粉。' } },
    { vn: 'Uống', zh: '喝', ex: { vn: 'Tôi uống nước.', zh: '我喝水。' } },
    { vn: 'Ngủ', zh: '睡', ex: { vn: 'Tôi ngủ sớm.', zh: '我早睡。' } },
    { vn: 'Thích', zh: '喜欢', ex: { vn: 'Tôi thích Việt Nam.', zh: '我喜欢越南。' } },
    { vn: 'Biết', zh: '知道', ex: { vn: 'Bạn có biết không?', zh: '你知道吗？' } },
    { vn: 'Hiểu', zh: '懂', ex: { vn: 'Tôi hiểu rồi.', zh: '我懂了。' } },
    { vn: 'Nói', zh: '说', ex: { vn: 'Bạn nói tiếng Anh không?', zh: '你会说英语吗？' } },
    { vn: 'Nghe', zh: '听', ex: { vn: 'Tôi nghe nhạc.', zh: '我听音乐。' } },
    { vn: 'Xem', zh: '看', ex: { vn: 'Tôi xem ti vi.', zh: '我看电视。' } },
    { vn: 'Làm', zh: '做', ex: { vn: 'Tôi làm việc.', zh: '我工作。' } },
    { vn: 'Học', zh: '学', ex: { vn: 'Tôi học tiếng Việt.', zh: '我学越南语。' } },
    { vn: 'Dạy', zh: '教', ex: { vn: 'Cô ấy dạy tiếng Trung.', zh: '她教中文。' } },
    { vn: 'Viết', zh: '写', ex: { vn: 'Tôi viết thư.', zh: '我写信。' } },
    { vn: 'Đọc', zh: '读', ex: { vn: 'Tôi đọc sách.', zh: '我读书。' } },
    { vn: 'Mở', zh: '开', ex: { vn: 'Mở cửa đi.', zh: '开门吧。' } },
    { vn: 'Đóng', zh: '关', ex: { vn: 'Đóng cửa lại.', zh: '把门关上。' } },
    { vn: 'Giúp', zh: '帮助', ex: { vn: 'Cảm ơn bạn giúp tôi.', zh: '谢谢你帮我。' } },
    { vn: 'Chạy', zh: '跑', ex: { vn: 'Tôi chạy mỗi sáng.', zh: '我每天早上跑步。' } },
    { vn: 'Đi bộ', zh: '走路', ex: { vn: 'Chúng ta đi bộ nhé.', zh: '我们走路吧。' } },
    { vn: 'Nghỉ', zh: '休息', ex: { vn: 'Tôi muốn nghỉ một chút.', zh: '我想休息一下。' } },
    { vn: 'Chờ', zh: '等', ex: { vn: 'Xin chờ một lát.', zh: '请等一下。' } },
    { vn: 'Mua sắm', zh: '购物', ex: { vn: 'Cuối tuần tôi hay mua sắm.', zh: '周末我爱逛街。' } },
  ]},
  { cat: '方位与疑问', icon: '📍', words: [
    { vn: 'Đâu', zh: '哪里', ex: { vn: 'Nhà vệ sinh ở đâu?', zh: '厕所在哪里？' } },
    { vn: 'Đây', zh: '这里', ex: { vn: 'Đây là nhà tôi.', zh: '这是我家。' } },
    { vn: 'Đó', zh: '那里', ex: { vn: 'Đó là trường học.', zh: '那是学校。' } },
    { vn: 'Trái', zh: '左', ex: { vn: 'Rẽ trái.', zh: '向左转。' } },
    { vn: 'Phải', zh: '右', ex: { vn: 'Rẽ phải.', zh: '向右转。' } },
    { vn: 'Trước', zh: '前', ex: { vn: 'Đứng trước cửa.', zh: '站在门前。' } },
    { vn: 'Sau', zh: '后', ex: { vn: 'Sau nhà có một cái cây.', zh: '屋后有一棵树。' } },
    { vn: 'Gần', zh: '近', ex: { vn: 'Gần đây thôi.', zh: '就在附近。' } },
    { vn: 'Xa', zh: '远', ex: { vn: 'Xa quá.', zh: '太远了。' } },
    { vn: 'Trên', zh: '上', ex: { vn: 'Sách ở trên bàn.', zh: '书在桌子上。' } },
    { vn: 'Dưới', zh: '下', ex: { vn: 'Mèo nằm dưới bàn.', zh: '猫在桌下。' } },
    { vn: 'Trong', zh: '里', ex: { vn: 'Tiền ở trong túi.', zh: '钱在口袋里。' } },
    { vn: 'Ngoài', zh: '外', ex: { vn: 'Cô ấy đợi ngoài cửa.', zh: '她等在门外。' } },
    { vn: 'Bên cạnh', zh: '旁边', ex: { vn: 'Ngồi bên cạnh tôi.', zh: '坐我旁边。' } },
    { vn: 'Giữa', zh: '中间', ex: { vn: 'Ở giữa phòng.', zh: '在房间中间。' } },
    { vn: 'Tại sao', zh: '为什么', ex: { vn: 'Tại sao muộn thế?', zh: '为什么这么晚？' } },
    { vn: 'Khi nào', zh: '什么时候', ex: { vn: 'Khi nào bạn đi?', zh: '你什么时候走？' } },
    { vn: 'Như thế nào', zh: '怎么样', ex: { vn: 'Việt Nam như thế nào?', zh: '越南怎么样？' } },
  ]},
  { cat: '旅行实用', icon: '🎒', words: [
    { vn: 'Hộ chiếu', zh: '护照', ex: { vn: 'Tôi mất hộ chiếu.', zh: '我丢了护照。' } },
    { vn: 'Visa', zh: '签证', ex: { vn: 'Tôi cần làm visa.', zh: '我需要办签证。' } },
    { vn: 'Vali', zh: '行李箱', ex: { vn: 'Vali nặng quá.', zh: '行李箱好重。' } },
    { vn: 'Quà', zh: '礼物', ex: { vn: 'Tôi mua quà cho bạn.', zh: '我给你买礼物。' } },
    { vn: 'Ảnh', zh: '照片', ex: { vn: 'Chụp ảnh nhé!', zh: '拍照吧！' } },
    { vn: 'Bản đồ', zh: '地图', ex: { vn: 'Xem bản đồ đi.', zh: '看地图吧。' } },
    { vn: 'Danh bạ', zh: '通讯录', ex: { vn: 'Mở danh bạ.', zh: '打开通讯录。' } },
    { vn: 'Điện thoại', zh: '电话', ex: { vn: 'Điện thoại của tôi hỏng.', zh: '我的电话坏了。' } },
    { vn: 'Internet', zh: '网络', ex: { vn: 'Internet chậm quá.', zh: '网络太慢了。' } },
    { vn: 'Sim', zh: '电话卡', ex: { vn: 'Tôi mua một chiếc sim.', zh: '我买一张电话卡。' } },
    { vn: 'Chuyến đi', zh: '旅程', ex: { vn: 'Chuyến đi rất vui.', zh: '旅程很开心。' } },
    { vn: 'Hướng dẫn viên', zh: '导游', ex: { vn: 'Hướng dẫn viên nói tiếng Trung.', zh: '导游会说中文。' } },
    { vn: 'Du lịch', zh: '旅游', ex: { vn: 'Tôi thích du lịch.', zh: '我喜欢旅游。' } },
    { vn: 'Kỳ nghỉ', zh: '假期', ex: { vn: 'Kỳ nghỉ hè dài.', zh: '暑假很长。' } },
    { vn: 'Lịch trình', zh: '行程', ex: { vn: 'Lịch trình hôm nay kín.', zh: '今天行程排满了。' } },
    { vn: 'Đặt vé', zh: '订票', ex: { vn: 'Tôi đặt vé máy bay.', zh: '我订了机票。' } },
    { vn: 'Nhận phòng', zh: '入住', ex: { vn: 'Mấy giờ nhận phòng?', zh: '几点入住？' } },
    { vn: 'Trả phòng', zh: '退房', ex: { vn: 'Trả phòng trước 12h.', zh: '12点前退房。' } },
  ]},
  { cat: '工作与职场', icon: '💼', words: [
    { vn: 'Công việc', zh: '工作', ex: { vn: 'Công việc của tôi bận.', zh: '我的工作很忙。' } },
    { vn: 'Văn phòng', zh: '办公室', ex: { vn: 'Tôi làm ở văn phòng.', zh: '我在办公室工作。' } },
    { vn: 'Sếp', zh: '老板', ex: { vn: 'Sếp tôi rất tốt.', zh: '我老板很好。' } },
    { vn: 'Đồng nghiệp', zh: '同事', ex: { vn: 'Đồng nghiệp thân thiện.', zh: '同事很友好。' } },
    { vn: 'Cuộc họp', zh: '会议', ex: { vn: 'Chiều nay có cuộc họp.', zh: '今天下午有会。' } },
    { vn: 'Lương', zh: '工资', ex: { vn: 'Lương tháng này cao.', zh: '这个月工资高。' } },
    { vn: 'Nghỉ phép', zh: '请假', ex: { vn: 'Tôi xin nghỉ phép.', zh: '我请个假。' } },
    { vn: 'Bận', zh: '忙', ex: { vn: 'Tuần này tôi bận.', zh: '这周我忙。' } },
    { vn: 'Rảnh', zh: '闲', ex: { vn: 'Cuối tuần tôi rảnh.', zh: '周末我有空。' } },
    { vn: 'Email', zh: '邮件', ex: { vn: 'Tôi gửi email cho sếp.', zh: '我给老板发邮件。' } },
    { vn: 'Máy tính', zh: '电脑', ex: { vn: 'Máy tính của tôi hỏng.', zh: '我的电脑坏了。' } },
    { vn: 'Giấy', zh: '纸', ex: { vn: 'Cho tôi một tờ giấy.', zh: '给我一张纸。' } },
    { vn: 'Bút', zh: '笔', ex: { vn: 'Cây bút này viết tốt.', zh: '这支笔好写。' } },
    { vn: 'In', zh: '打印', ex: { vn: 'Tôi cần in tài liệu.', zh: '我需要打印资料。' } },
    { vn: 'Ký', zh: '签字', ex: { vn: 'Mời bạn ký ở đây.', zh: '请在这里签字。' } },
    { vn: 'Khách hàng', zh: '客户', ex: { vn: 'Khách hàng rất khó tính.', zh: '客户很难缠。' } },
    { vn: 'Bán hàng', zh: '销售', ex: { vn: 'Cô ấy làm bán hàng.', zh: '她做销售。' } },
    { vn: 'Công ty', zh: '公司', ex: { vn: 'Công ty tôi ở trung tâm.', zh: '我公司在市中心。' } },
    { vn: 'Làm việc', zh: '上班', ex: { vn: 'Tôi làm việc từ thứ Hai.', zh: '我周一开始上班。' } },
    { vn: 'Nghỉ hưu', zh: '退休', ex: { vn: 'Ông tôi sắp nghỉ hưu.', zh: '我爷爷快退休了。' } },
  ]},
  { cat: '情绪与感受', icon: '😊', words: [
    { vn: 'Vui', zh: '开心', ex: { vn: 'Hôm nay tôi rất vui.', zh: '今天我很开心。' } },
    { vn: 'Buồn', zh: '难过', ex: { vn: 'Tại sao bạn buồn?', zh: '你为什么难过？' } },
    { vn: 'Giận', zh: '生气', ex: { vn: 'Đừng giận tôi.', zh: '别生我的气。' } },
    { vn: 'Sợ', zh: '害怕', ex: { vn: 'Tôi sợ độ cao.', zh: '我恐高。' } },
    { vn: 'Ngạc nhiên', zh: '惊讶', ex: { vn: 'Tôi rất ngạc nhiên.', zh: '我很惊讶。' } },
    { vn: 'Xấu hổ', zh: '害羞', ex: { vn: 'Con bé xấu hổ quá.', zh: '小姑娘太害羞了。' } },
    { vn: 'Mệt mỏi', zh: '疲惫', ex: { vn: 'Sau chuyến đi tôi mệt mỏi.', zh: '旅行后我很疲惫。' } },
    { vn: 'Yên tâm', zh: '安心', ex: { vn: 'Bạn yên tâm nhé.', zh: '你放心吧。' } },
    { vn: 'Lo lắng', zh: '担心', ex: { vn: 'Tôi lo lắng cho con.', zh: '我担心孩子。' } },
    { vn: 'Hy vọng', zh: '希望', ex: { vn: 'Tôi hy vọng thành công.', zh: '我希望成功。' } },
    { vn: 'Thất vọng', zh: '失望', ex: { vn: 'Tôi thất vọng quá.', zh: '我很失望。' } },
    { vn: 'Tự hào', zh: '骄傲', ex: { vn: 'Tôi tự hào về bạn.', zh: '我为你骄傲。' } },
    { vn: 'Cô đơn', zh: '孤单', ex: { vn: 'Ở xa nhà tôi thấy cô đơn.', zh: '离家在外我觉得孤单。' } },
    { vn: 'Hạnh phúc', zh: '幸福', ex: { vn: 'Gia đình tôi hạnh phúc.', zh: '我家很幸福。' } },
    { vn: 'Buồn ngủ', zh: '困', ex: { vn: 'Tôi buồn ngủ rồi.', zh: '我困了。' } },
    { vn: 'Đói', zh: '饿', ex: { vn: 'Tôi đói bụng.', zh: '我肚子饿了。' } },
    { vn: 'Khát', zh: '渴', ex: { vn: 'Tôi khát nước.', zh: '我渴了。' } },
    { vn: 'Nóng nực', zh: '闷热', ex: { vn: 'Trời nóng nực quá.', zh: '天气闷热。' } },
    { vn: 'Mát', zh: '凉爽', ex: { vn: 'Gió biển mát rượi.', zh: '海风凉爽。' } },
    { vn: 'Thoải mái', zh: '舒服', ex: { vn: 'Chiếc giường này thoải mái.', zh: '这张床很舒服。' } },
  ]},
  { cat: '颜色与形状', icon: '🎨', words: [
    { vn: 'Màu đỏ', zh: '红色' },
    { vn: 'Màu xanh', zh: '绿色/蓝色' },
    { vn: 'Màu vàng', zh: '黄色' },
    { vn: 'Màu trắng', zh: '白色' },
    { vn: 'Màu đen', zh: '黑色' },
    { vn: 'Màu hồng', zh: '粉色' },
    { vn: 'Màu tím', zh: '紫色' },
    { vn: 'Màu nâu', zh: '棕色' },
    { vn: 'Tròn', zh: '圆', ex: { vn: 'Quả táo tròn.', zh: '苹果是圆的。' } },
    { vn: 'Vuông', zh: '方', ex: { vn: 'Cái bàn vuông.', zh: '桌子是方的。' } },
    { vn: 'Dài', zh: '长', ex: { vn: 'Sông này dài.', zh: '这条河很长。' } },
    { vn: 'Ngắn', zh: '短', ex: { vn: 'Tóc cô ấy ngắn.', zh: '她头发很短。' } },
    { vn: 'Cao', zh: '高', ex: { vn: 'Anh ấy rất cao.', zh: '他很高。' } },
    { vn: 'Thấp', zh: '矮', ex: { vn: 'Bức tường thấp.', zh: '墙很矮。' } },
    { vn: 'Lớn', zh: '大', ex: { vn: 'Cái nhà lớn.', zh: '房子很大。' } },
    { vn: 'Nhỏ', zh: '小', ex: { vn: 'Con mèo nhỏ.', zh: '小猫很小。' } },
  ]},
  { cat: '身体部位', icon: '🧍', words: [
    { vn: 'Đầu', zh: '头' },
    { vn: 'Mắt', zh: '眼睛', ex: { vn: 'Mắt tôi mệt.', zh: '我的眼睛累了。' } },
    { vn: 'Mũi', zh: '鼻子' },
    { vn: 'Miệng', zh: '嘴' },
    { vn: 'Tai', zh: '耳朵', ex: { vn: 'Tai tôi kém.', zh: '我听力不好。' } },
    { vn: 'Răng', zh: '牙' },
    { vn: 'Tóc', zh: '头发', ex: { vn: 'Tóc dài đẹp.', zh: '长发好看。' } },
    { vn: 'Mặt', zh: '脸', ex: { vn: 'Mặt cô ấy đỏ.', zh: '她脸红了。' } },
    { vn: 'Tay', zh: '手', ex: { vn: 'Tay phải viết.', zh: '右手写字。' } },
    { vn: 'Chân', zh: '脚', ex: { vn: 'Chân tôi đau.', zh: '我的脚疼。' } },
    { vn: 'Bụng', zh: '肚子' },
    { vn: 'Lưng', zh: '背', ex: { vn: 'Lưng tôi mỏi.', zh: '我背酸。' } },
    { vn: 'Tim', zh: '心脏', ex: { vn: 'Tim đập nhanh.', zh: '心跳很快。' } },
    { vn: 'Da', zh: '皮肤', ex: { vn: 'Da cô ấy trắng.', zh: '她皮肤白。' } },
    { vn: 'Cổ', zh: '脖子', ex: { vn: 'Cổ áo mới.', zh: '衣领是新的。' } },
    { vn: 'Vai', zh: '肩膀', ex: { vn: 'Vai tôi đau.', zh: '我肩膀疼。' } },
    { vn: 'Gối', zh: '膝盖', ex: { vn: 'Gối tôi bị thương.', zh: '我膝盖受伤了。' } },
    { vn: 'Ngón tay', zh: '手指', ex: { vn: 'Cắt ngón tay.', zh: '割到手指。' } },
  ]},
  { cat: '服饰与穿搭', icon: '👕', words: [
    { vn: 'Áo', zh: '上衣', ex: { vn: 'Áo này đẹp.', zh: '这件上衣好看。' } },
    { vn: 'Quần', zh: '裤子', ex: { vn: 'Quần jeans xanh.', zh: '蓝色牛仔裤。' } },
    { vn: 'Váy', zh: '裙子', ex: { vn: 'Cái váy dài.', zh: '长裙。' } },
    { vn: 'Giày', zh: '鞋', ex: { vn: 'Giày thể thao.', zh: '运动鞋。' } },
    { vn: 'Mũ', zh: '帽子', ex: { vn: 'Đội mũ đi nắng.', zh: '戴帽子防晒。' } },
    { vn: 'Túi xách', zh: '手提包', ex: { vn: 'Túi xách đắt tiền.', zh: '手提包很贵。' } },
    { vn: 'Áo sơ mi', zh: '衬衫', ex: { vn: 'Áo sơ mi trắng.', zh: '白衬衫。' } },
    { vn: 'Áo khoác', zh: '外套', ex: { vn: 'Mặc áo khoác đi.', zh: '穿上外套。' } },
    { vn: 'Vớ', zh: '袜子', ex: { vn: 'Đôi vớ mới.', zh: '新袜子。' } },
    { vn: 'Khăn quàng', zh: '围巾', ex: { vn: 'Khăn quàng ấm.', zh: '暖和围巾。' } },
    { vn: 'Đồng hồ', zh: '手表', ex: { vn: 'Đồng hồ Thụy Sĩ.', zh: '瑞士手表。' } },
    { vn: 'Kính', zh: '眼镜', ex: { vn: 'Kính râm cho nắng.', zh: '墨镜防晒。' } },
    { vn: 'Trang sức', zh: '首饰', ex: { vn: 'Trang sức bạc.', zh: '银首饰。' } },
    { vn: 'Mặc', zh: '穿', ex: { vn: 'Mặc gì hôm nay?', zh: '今天穿什么？' } },
    { vn: 'Cởi', zh: '脱', ex: { vn: 'Cởi áo đi.', zh: '把衣服脱了。' } },
    { vn: 'Giặt', zh: '洗（衣）', ex: { vn: 'Giặt quần áo.', zh: '洗衣服。' } },
  ]},
  { cat: '动物与植物', icon: '🐾', words: [
    { vn: 'Chó', zh: '狗', ex: { vn: 'Chú chó dễ thương.', zh: '小狗很可爱。' } },
    { vn: 'Mèo', zh: '猫', ex: { vn: 'Con mèo lười.', zh: '懒猫。' } },
    { vn: 'Gà', zh: '鸡' },
    { vn: 'Heo', zh: '猪', ex: { vn: 'Con heo mập.', zh: '胖猪。' } },
    { vn: 'Bò', zh: '牛' },
    { vn: 'Cá', zh: '鱼' },
    { vn: 'Vịt', zh: '鸭', ex: { vn: 'Vịt bơi trên hồ.', zh: '鸭子在湖上游。' } },
    { vn: 'Chim', zh: '鸟', ex: { vn: 'Chim hót trên cây.', zh: '鸟在树上叫。' } },
    { vn: 'Ngựa', zh: '马', ex: { vn: 'Ngựa chạy nhanh.', zh: '马跑得快。' } },
    { vn: 'Voi', zh: '大象', ex: { vn: 'Voi ở vườn thú.', zh: '动物园的大象。' } },
    { vn: 'Khỉ', zh: '猴子', ex: { vn: 'Con khỉ tinh nghịch.', zh: '调皮的猴子。' } },
    { vn: 'Hoa hồng', zh: '玫瑰', ex: { vn: 'Bó hoa hồng.', zh: '一束玫瑰。' } },
    { vn: 'Cây', zh: '树' },
    { vn: 'Lá', zh: '叶子', ex: { vn: 'Lá xanh biếc.', zh: '碧绿的叶子。' } },
    { vn: 'Trái cây', zh: '水果', ex: { vn: 'Trái cây tươi.', zh: '新鲜水果。' } },
    { vn: 'Rừng', zh: '森林', ex: { vn: 'Rừng rậm nhiệt đới.', zh: '热带雨林。' } },
  ]},
  { cat: '应急求助', icon: '🆘', words: [
    { vn: 'Cứu tôi!', zh: '救命！', ex: { vn: 'Cứu tôi với!', zh: '救救我！' } },
    { vn: 'Tôi bị lạc.', zh: '我迷路了。', ex: { vn: 'Xin lỗi, tôi bị lạc.', zh: '对不起，我迷路了。' } },
    { vn: 'Tôi cần bác sĩ.', zh: '我需要医生。', ex: { vn: 'Giúp tôi, tôi cần bác sĩ.', zh: '帮帮我，我需要医生。' } },
    { vn: 'Cảnh sát', zh: '警察', ex: { vn: 'Gọi cảnh sát đi.', zh: '叫警察吧。' } },
    { vn: 'Đồn cảnh sát', zh: '警察局', ex: { vn: 'Đồn cảnh sát ở đâu?', zh: '警察局在哪？' } },
    { vn: 'Mất', zh: '丢失', ex: { vn: 'Tôi mất ví.', zh: '我丢了钱包。' } },
    { vn: 'Trộm', zh: '小偷', ex: { vn: 'Có trộm!', zh: '有贼！' } },
    { vn: 'Nguy hiểm', zh: '危险', ex: { vn: 'Chỗ này nguy hiểm.', zh: '这地方危险。' } },
    { vn: 'Hỏa hoạn', zh: '火灾', ex: { vn: 'Có hỏa hoạn!', zh: '着火了！' } },
    { vn: 'Tai nạn', zh: '事故', ex: { vn: 'Tai nạn giao thông.', zh: '交通事故。' } },
    { vn: 'Xe cứu thương', zh: '救护车', ex: { vn: 'Gọi xe cứu thương.', zh: '叫救护车。' } },
    { vn: 'Số điện thoại', zh: '电话号码', ex: { vn: 'Số điện thoại của bạn?', zh: '你的电话号码？' } },
    { vn: 'Gọi', zh: '打电话', ex: { vn: 'Gọi cho tôi nhé.', zh: '给我打电话吧。' } },
    { vn: 'Giúp đỡ', zh: '帮助', ex: { vn: 'Cần sự giúp đỡ.', zh: '需要帮助。' } },
    { vn: 'Tôi không biết', zh: '我不知道', ex: { vn: 'Xin lỗi, tôi không biết.', zh: '抱歉，我不知道。' } },
    { vn: 'Nói chậm lại', zh: '说慢点', ex: { vn: 'Xin nói chậm lại.', zh: '请说慢一点。' } },
    { vn: 'Lặp lại', zh: '重复', ex: { vn: 'Lặp lại được không?', zh: '能重复一遍吗？' } },
    { vn: 'An toàn', zh: '安全', ex: { vn: 'Về nhà an toàn.', zh: '平安回家。' } },
  ]},
  { cat: '数字扩展 11-100', icon: '🔢', words: [
    { vn: 'Mười một', zh: '十一' },
    { vn: 'Mười hai', zh: '十二' },
    { vn: 'Mười ba', zh: '十三' },
    { vn: 'Mười bốn', zh: '十四' },
    { vn: 'Mười lăm', zh: '十五' },
    { vn: 'Mười sáu', zh: '十六' },
    { vn: 'Mười bảy', zh: '十七' },
    { vn: 'Mười tám', zh: '十八' },
    { vn: 'Mười chín', zh: '十九' },
    { vn: 'Hai mươi', zh: '二十' },
    { vn: 'Ba mươi', zh: '三十' },
    { vn: 'Bốn mươi', zh: '四十' },
    { vn: 'Năm mươi', zh: '五十' },
    { vn: 'Một trăm', zh: '一百' },
    { vn: 'Nửa', zh: '一半', ex: { vn: 'Nửa tiếng nữa.', zh: '再过半小时。' } },
    { vn: 'Đôi', zh: '一双/对', ex: { vn: 'Một đôi giày.', zh: '一双鞋。' } },
  ]},
];
