/* 越南语生活高频词（按主题分组，第一波约 120 词；后续可继续补充到 300–500）
   数据结构：VN_TOPIC_WORDS = [{ cat, icon, words:[{ vn, zh, ex? }] }]
   ex 为可选：该词的实用例句 { vn, zh }，用于口语练习「💡 例句」展开。
   本文件在 app.js 之前加载，VN_TOPIC_WORDS 为全局变量。 */
const VN_TOPIC_WORDS = [
  { cat: '问候与社交', icon: '👋', words: [
    { vn: 'Xin chào', zh: '你好' },
    { vn: 'Tạm biệt', zh: '再见' },
    { vn: 'Cảm ơn', zh: '谢谢' },
    { vn: 'Không có gì', zh: '不客气' },
    { vn: 'Xin lỗi', zh: '对不起' },
    { vn: 'Tên tôi là…', zh: '我叫……' },
    { vn: 'Bạn tên là gì?', zh: '你叫什么名字？' },
    { vn: 'Rất vui được gặp bạn.', zh: '很高兴认识你。' },
    { vn: 'Không sao.', zh: '没关系。' },
    { vn: 'Bạn khỏe không?', zh: '你好吗？', ex: { vn: 'Bạn khỏe không? Tôi khỏe, cảm ơn.', zh: '你好吗？我很好，谢谢。' } },
  ]},
  { cat: '餐饮', icon: '🍜', words: [
    { vn: 'Phở', zh: '河粉', ex: { vn: 'Cho tôi một bát phở.', zh: '给我一碗河粉。' } },
    { vn: 'Cơm', zh: '米饭' },
    { vn: 'Bánh mì', zh: '面包' },
    { vn: 'Nước', zh: '水', ex: { vn: 'Tôi muốn một chai nước.', zh: '我要一瓶水。' } },
    { vn: 'Cà phê', zh: '咖啡' },
    { vn: 'Trà', zh: '茶' },
    { vn: 'Thịt', zh: '肉' },
    { vn: 'Cá', zh: '鱼' },
    { vn: 'Rau', zh: '蔬菜' },
    { vn: 'Ngon', zh: '好吃', ex: { vn: 'Món này ngon quá!', zh: '这道菜太好吃了！' } },
  ]},
  { cat: '住宿', icon: '🛏️', words: [
    { vn: 'Khách sạn', zh: '酒店' },
    { vn: 'Phòng', zh: '房间' },
    { vn: 'Nhà', zh: '房子' },
    { vn: 'Giường', zh: '床' },
    { vn: 'Nhà vệ sinh', zh: '厕所', ex: { vn: 'Nhà vệ sinh ở đâu?', zh: '厕所在哪里？' } },
    { vn: 'Nóng', zh: '热' },
    { vn: 'Lạnh', zh: '冷' },
    { vn: 'Sạch', zh: '干净' },
    { vn: 'Bẩn', zh: '脏' },
    { vn: 'Chìa khóa', zh: '钥匙' },
  ]},
  { cat: '交通出行', icon: '🚕', words: [
    { vn: 'Xe buýt', zh: '公交车' },
    { vn: 'Xe taxi', zh: '出租车' },
    { vn: 'Xe máy', zh: '摩托车' },
    { vn: 'Sân bay', zh: '机场', ex: { vn: 'Sân bay ở đâu?', zh: '机场在哪里？' } },
    { vn: 'Ga tàu', zh: '火车站' },
    { vn: 'Đi', zh: '去', ex: { vn: 'Tôi đi Việt Nam.', zh: '我去越南。' } },
    { vn: 'Đến', zh: '到' },
    { vn: 'Về', zh: '回' },
    { vn: 'Trạm dừng', zh: '车站' },
    { vn: 'Vé', zh: '票' },
  ]},
  { cat: '购物', icon: '🛍️', words: [
    { vn: 'Tiền', zh: '钱' },
    { vn: 'Bao nhiêu', zh: '多少', ex: { vn: 'Cái này bao nhiêu tiền?', zh: '这个多少钱？' } },
    { vn: 'Đắt', zh: '贵' },
    { vn: 'Rẻ', zh: '便宜' },
    { vn: 'Mua', zh: '买', ex: { vn: 'Tôi muốn mua cái này.', zh: '我想买这个。' } },
    { vn: 'Bán', zh: '卖' },
    { vn: 'Chợ', zh: '市场' },
    { vn: 'Cửa hàng', zh: '商店' },
    { vn: 'Màu', zh: '颜色' },
    { vn: 'Kích thước', zh: '尺寸' },
  ]},
  { cat: '健康医疗', icon: '💊', words: [
    { vn: 'Bác sĩ', zh: '医生', ex: { vn: 'Tôi cần gặp bác sĩ.', zh: '我需要看医生。' } },
    { vn: 'Thuốc', zh: '药' },
    { vn: 'Bệnh viện', zh: '医院' },
    { vn: 'Đau', zh: '疼', ex: { vn: 'Tôi bị đau đầu.', zh: '我头疼。' } },
    { vn: 'Sốt', zh: '发烧' },
    { vn: 'Mệt', zh: '累' },
    { vn: 'Cứu', zh: '救', ex: { vn: 'Cứu tôi với!', zh: '救命！' } },
    { vn: 'Hiệu thuốc', zh: '药店' },
    { vn: 'Tiêm', zh: '打针' },
    { vn: 'Nhức', zh: '痛' },
  ]},
  { cat: '人物与称谓', icon: '👨‍👩‍👧', words: [
    { vn: 'Tôi', zh: '我', ex: { vn: 'Tôi là người Trung Quốc.', zh: '我是中国人。' } },
    { vn: 'Bạn', zh: '你 / 朋友' },
    { vn: 'Anh', zh: '哥哥 / 你（男）' },
    { vn: 'Chị', zh: '姐姐 / 你（女）' },
    { vn: 'Em', zh: '弟弟 / 妹妹' },
    { vn: 'Bố', zh: '爸爸' },
    { vn: 'Mẹ', zh: '妈妈' },
    { vn: 'Con', zh: '孩子' },
    { vn: 'Người', zh: '人' },
    { vn: 'Gia đình', zh: '家庭' },
  ]},
  { cat: '时间与数字', icon: '⏰', words: [
    { vn: 'Hôm nay', zh: '今天', ex: { vn: 'Hôm nay trời đẹp.', zh: '今天天气好。' } },
    { vn: 'Ngày', zh: '天' },
    { vn: 'Tháng', zh: '月' },
    { vn: 'Năm', zh: '年' },
    { vn: 'Giờ', zh: '小时 / 钟点' },
    { vn: 'Sáng', zh: '早上' },
    { vn: 'Chiều', zh: '下午' },
    { vn: 'Tối', zh: '晚上' },
    { vn: 'Một', zh: '一' },
    { vn: 'Hai', zh: '二' },
  ]},
  { cat: '天气与自然', icon: '🌤️', words: [
    { vn: 'Trời', zh: '天 / 天气', ex: { vn: 'Trời đẹp quá!', zh: '天气真好！' } },
    { vn: 'Mưa', zh: '雨' },
    { vn: 'Nắng', zh: '晴' },
    { vn: 'Gió', zh: '风' },
    { vn: 'Núi', zh: '山' },
    { vn: 'Sông', zh: '河' },
    { vn: 'Biển', zh: '海' },
    { vn: 'Cây', zh: '树' },
    { vn: 'Hoa', zh: '花' },
    { vn: 'Mặt trời', zh: '太阳' },
  ]},
  { cat: '常用动词', icon: '💬', words: [
    { vn: 'Ăn', zh: '吃', ex: { vn: 'Tôi ăn phở.', zh: '我吃河粉。' } },
    { vn: 'Uống', zh: '喝' },
    { vn: 'Ngủ', zh: '睡' },
    { vn: 'Thích', zh: '喜欢', ex: { vn: 'Tôi thích Việt Nam.', zh: '我喜欢越南。' } },
    { vn: 'Biết', zh: '知道' },
    { vn: 'Hiểu', zh: '懂' },
    { vn: 'Nói', zh: '说', ex: { vn: 'Bạn nói tiếng Anh không?', zh: '你会说英语吗？' } },
    { vn: 'Nghe', zh: '听' },
    { vn: 'Xem', zh: '看' },
    { vn: 'Làm', zh: '做' },
  ]},
  { cat: '方位与疑问', icon: '📍', words: [
    { vn: 'Đâu', zh: '哪里', ex: { vn: 'Nhà vệ sinh ở đâu?', zh: '厕所在哪里？' } },
    { vn: 'Đây', zh: '这里' },
    { vn: 'Đó', zh: '那里' },
    { vn: 'Trái', zh: '左' },
    { vn: 'Phải', zh: '右' },
    { vn: 'Trước', zh: '前' },
    { vn: 'Sau', zh: '后' },
    { vn: 'Gần', zh: '近' },
    { vn: 'Xa', zh: '远' },
    { vn: 'Trên', zh: '上' },
  ]},
  { cat: '旅行实用', icon: '🎒', words: [
    { vn: 'Hộ chiếu', zh: '护照', ex: { vn: 'Tôi mất hộ chiếu.', zh: '我丢了护照。' } },
    { vn: 'Visa', zh: '签证' },
    { vn: 'Vali', zh: '行李箱' },
    { vn: 'Quà', zh: '礼物' },
    { vn: 'Ảnh', zh: '照片' },
    { vn: 'Bản đồ', zh: '地图' },
    { vn: 'Danh bạ', zh: '通讯录' },
    { vn: 'Điện thoại', zh: '电话' },
    { vn: 'Internet', zh: '网络' },
    { vn: 'Sim', zh: '电话卡' },
  ]},
];
